version: '3.8'

services: 
  app:
  image: tomrosert/wp-codespace:latest
  volumes:
    - ../..:/workspaces:cached
  ports:
    - 80:80
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: wordpress
    WORDPRESS_DB_NAME: wordpress
  command: ["apache2-foreground"]

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db

volumes:
  mariadb-data:
