services:
  app:
    image: wordpress:6.8-apache
    container_name: wp_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../..:/var/www/html:cached
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1  # デバッグ有効化
    depends_on:
      - db

  db:
    image: mariadb:11.1
    container_name: wp_db
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp_pma
    depends_on:
      - db
    ports:
      - "81:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress

volumes:
  mariadb-data:
